### ISSUE TITLE
Do we keep the domain name TiWim.tk?

### ISSUE THREAD

**Issue by TiWim** [TiWim/TiWim.github.io#12]
There is a problem to acces the pages with the url.
On the other hand, pages that are not really released will not be accessible.

**Comment by rebmema** [comment]
[This](https://openclassrooms.com/forum/sujet/probleme-d-url-avec-tk-28822) is what you mean ?
Why did you set up this domain name in the first place ? Url shortening ? Anonymity  ?

**Comment by TiWim** [comment]
Ok, yes it was for anonymity. I changed my name. It ok so.
